http:
  host: 'localhost'
  port: 3333
  globalPrefix: 'api'

db:
  type: 'postgres'
  url: 'localhost'
  port: 5431
  database: 'todoApp'
  synchronize: true
  entities: ["../dist/packages/todo-api/**/*.entity{ .ts,.js}"]
  username: 'postgres'
  password: 'docker'
  "migrations": ["../dist/packages/todo-api/migrations/*{.ts,.js}"]
