http:
  host: 'localhost'
  port: 3333
  globalPrefix: 'api'

db:
  type: 'postgres'
  url: 'localhost'
  port: 5431
  database: 'todoApp'
  synchronize: true
  entities: []
  username: 'postgres'
  password: 'docker'

