http:
  host: 'localhost'
  port: 3333
  globalPrefix: 'api'

db:
  type: 'postgres'
  url: 'host.docker.internal'
  port: 5431
  database: 'todoApp'
  synchronize: true
  entities: ['dist/packages/todo-api/**/*.entity.ts}']
  username: 'postgres'
  password: 'docker'
  migrations: ['packages/src/todo-api/migrations/**/*.ts']
